### ISSUE TITLE
Opening new tab does not give it focus

### ISSUE THREAD

**Issue by bronzer** [benbasson/newtabhomepage#1]
With the latest nightly builds opening  a new tab via shortcut or button opens the homepage tab but focus remains on your current tab.

**Comment by meyerweb** [comment]
Confirmed; seeing this in OS X.  With the extension disabled, the tab-focus behavior is correct.

**Comment by pwizla** [comment]
Confirmed.

**Comment by benbasson** [comment]
This should be resolved in the latest version (as the extension has been rewritten to use in-built Firefox code to handle the tab opening). Please confirm if this is still a problem once you've been upgraded to 0.5? Thanks.

**Comment by bronzer** [comment]
This does fix the issue thanks. Although I would like it to give focus to the tab content rather than the URL bar. I was using an older build (4.1?) in order to preserve that functionality. Is that possible in the latest build?

Date: Sun, 27 Sep 2015 02:53:50 -0700

**Comment by corebe3** [comment]
Latest version installed and new tab does give me my home page but leaves focus on url in address bar, not in the Google search field where I would prefer it.  Thanks

**Comment by benbasson** [comment]
Giving focus to content is covered by issue #2, and is actually trickier than you might think. I will keep it in mind, but so far I've never managed to find a reliable way of doing it. I'd rather release code that works than something that half-works and annoys people even more :-)
