### ISSUE TITLE
Text input in search bar and not in URL bar

### ISSUE THREAD

**Issue by kaypoush** [benbasson/newtabhomepage#10]
Hello,

Your extension works but there is a little problem for me. When a new tab is opened and shows my homepage (Google), the URL part is selected and if I want to search something I need to click on the search bar from the website otherwise it'll just replace the URL.

Can you please put the text input automatically in the search bar of the website and not in the URL of Firefox? At least give us the option to do it so if we want. 

I know it's possible because when I click on the home button in Firefox and my homepage shows up, the search bar of Google is automatically selected and I can write in it without the one click.

Thank you.

**Comment by mimamue** [comment]
I want that desperately, too!

**Comment by benbasson** [comment]
This is covered by issue #2
