### ISSUE TITLE
Focus stopped working in FF 45

### ISSUE THREAD

**Issue by davidf3329** [benbasson/newtabhomepage#11]
When clicking on a new tab, it opens the home page but does not focus on the new tab. Was working ok until FF 45.

**Comment by mimamue** [comment]
Do you mean that when opening a new tab (e. g. google,com) the cursor is only placed into the URL bar, instead of being placed to the first text field, in this case Google's search field?
If you mean that, I totally agree, for me this behaviour is really annoying, as well ... :-(
Would be great if that could be fixed!
Thanks a lot in advance,
Michael

**Comment by davidf3329** [comment]
Hi Michael,

What's happening is when a new tab is opened, the focus doesn't change to the new tab. You have to click a second time on the tab. 

You are referring to focus on the search field, but it's actually the new browser window/tab that doesn't take focus when it's opened. I have to click a second time to go to the new window/tab. 

How that helps clear it up. 

Kindly
David

**Comment by mimamue** [comment]
Hi David,
yeah, it wasn't really unclear ... but if a new tab opens in the background and therefore I have to click a 2nd time on that tab, OR if the new tab DOES open in the foreground (but with cursor in the URL bar) and I have to click a 2nd time into the desired text field, doesn't make any difference in the end ... both ways need a 2nd click, that's what I meant ;-)
So the 2nd "solution", with the new tab in the foreground (with the  latest version of this AddOn), at least gives me the option to change the URL directly (if I want that), without ANY further click ... ;-)
But anyway, I really appreciated your hint with version 0.4.3.1, it's always great to be able to chose between more than one option and find out which option appears as the best ;-)
Have a great time,
Michael

**Comment by benbasson** [comment]
New Tab Homepage doesn't affect whether a tab is automatically selected or not - that happens outside of this add-on (i.e. with Firefox or other add-on settings).

If you have the problem that, once the new tab is selected, the focus is not placed where you want it (page or location bar) then that's covered by #2.
