### ISSUE TITLE
Doesn't work quite right with TabGroups Manager

### ISSUE THREAD

**Issue by wbt** [benbasson/newtabhomepage#12]
When [TabGroups Manager](https://addons.mozilla.org/en-US/firefox/addon/tabgroups-manager/) is installed and a new TabGroup is opened, this extension does not load the homepage in the first New Tab of that group.

**Comment by benbasson** [comment]
Sorry, but I'm not particularly interested in investigating compatibility with heavier duty tab related add-ons. I suggest you ask them nicely to add this functionality directly into their add-on if it's not already there.
