### ISSUE TITLE
PDF convert HQ by my way causes tab not to open in homepage

### ISSUE THREAD

**Issue by jimdooris** [benbasson/newtabhomepage#13]
I recently installed  PDFConverterHQ by MyWay. now when I open a new tab it uses "http://hp.myway.com/pdfconverterhq/ttab02/index.html?coId=f2429317ec1c48e2ad4685e75d0e808b&subId=28768658164&ln=en&n=782a7d4a&ptb=089DEB46-A6B0-4DF7-9B00-B881DCA2752D&st=tab&p2=%5ECAM%5Exdm106%5ETTAB02%5Eus&si=28768658164" instead of my home page.,but pressing home returns to the correct home page

**Comment by benbasson** [comment]
I assume their add-on is hijacking the new tab function in the same way that mine does. I'd suggest that you take it up with the author of that add-on.
