### ISSUE TITLE
Appears to have stopped working in FF49

### ISSUE THREAD

**Issue by ghost** [benbasson/newtabhomepage#15]
NTHP appears to have been crippled by the upgrade to FF49. Was working fine under FF48. I am using multiple other add-ons but have not added any between the upgrades. Unfortunately, do not have time to investigate further.

**Comment by andreicristianpetcu** [comment]
Strange. I am on Firefox 52 (Nightly) and 51 (DevEdition) for quite some time and it always worked. Have you tried with a new Firefox profile?

**Comment by ghost** [comment]
Thanks for your feedback, Andrei. I'll bear it in mind. Unfortunately, |I haven't the time to investigate further at present. Admittedly, I maybe shouldn't be posting until  I have. However, the only thing that changed was the upgrade. It was working immediately before and not working immediately after I restarted FF. our suggestion is useful and it m\y also be complicated by other installed add-ons, but none of those have changed either. We'll see what happens in due course. I just thought that I should post an early advisory.

**Comment by benbasson** [comment]
Are you still having problems? Working fine for me in FF50.
