### ISSUE TITLE
Rewrite New Tab Homepage using WebExtensions APIs

### ISSUE THREAD

**Issue by benbasson** [benbasson/newtabhomepage#19]
Mozilla have announced plans to phase out all non-WebExtension add-ons by the end of 2017. While I consider this decision to be utterly insane (and half expect them to end up extending that deadline, if they have any users left to appease at that point), it's safe to assume that this add-on will have to be rewritten or will cease to exist at the end of 2017.

Current blockers in the WebExtensions API:

- <del>[Bug 1234150 - Support overriding newtab page from a webextension](https://bugzilla.mozilla.org/show_bug.cgi?id=1234150)</del>
- <del>[Bug 1322308 - Read homepage (and maybe other settings?) in a WebExtension](https://bugzilla.mozilla.org/show_bug.cgi?id=1322308)</del>

Not blocking, but relevant:

- <del>[Bug 1295072 - Awesomebar doesn't get focus when creating tab from chrome.tabs.create()](https://bugzilla.mozilla.org/show_bug.cgi?id=1295072)</del>

**Comment by dave-kennedy** [comment]
Looks like v54 adds support for overriding the new tab page URL in the package manifest: https://bugzilla.mozilla.org/show_bug.cgi?id=1234150

It doesn't allow the end user to specify an arbitrary URL through settings, but [Mike Kaply suggested a workaround](https://bugzilla.mozilla.org/show_bug.cgi?id=1234150#c39):

> You can allow the user to override the new tab page in an extension by simply setting the new tab page to a chrome URL in your extension and then having that chrome URL navigate to the correct page. (That's how you do it in the Chrome browser).

**Comment by benbasson** [comment]
Well, they've closed off Bug 1322308, but not in a way that actually meets the requirement, so I guess we'll soon find out whether that's the end of this add-on or if they're going to revisit the API.

**Comment by benbasson** [comment]
So I'm pretty sure I am done with the rewrite of this add-on and I'm pushing it to GitHub. 

Holding off on release for now because I'm damned if I can figure out which version of Firefox it'll be compatible with, but 57.0b8 doesn't seem to cut it. Fingers crossed that the APIs I need made it in time to be in the RC or final builds.

**Comment by benbasson** [comment]
Published on AMO.
