### ISSUE TITLE
"Cursor to page" option

### ISSUE THREAD

**Issue by tuttle** [benbasson/newtabhomepage#22]
The homepage I have set in my FF contains an input field that I would like to get focused immediately after the new tab is open so I can start writing into the field. Currently, the Location bar content is selected and focused, which state I don't need as it is easily reachable by pressing Ctrl-L.

Would it be possible, please?

It's really beyond me, why vanilla FF does not offer "Home page" among options for new tab itself when it is already possible to pick between popular pages and blank page.

Thanks for this neat extension.

**Comment by benbasson** [comment]
Fixed by #19
