### ISSUE TITLE
Problem with links on websites that open a new tab

### ISSUE THREAD

**Issue by Hilary247** [benbasson/newtabhomepage#26]
Using FireFox 57.0 and newtabhomepage 0.6.2 on a Windows 10 PC

With the add-on enabled, when clicking on a link on a page that opens a new tab, the requested page does not display properly. With the add-on disabled, the page is displayed correctly.

Steps to reproduce:
Go to Pinterest, log in and select a Pin. Click on the "Open" button.

A new tab is opened and goes busy briefly.
The resultant page is blank except for a tiny, tiny image in the top left-hand corner. This is the expected image but this is how it appears:

![capture](https://user-images.githubusercontent.com/33802584/32990069-1aac1b5c-cd1a-11e7-8f69-9b41fbd151af.JPG)

If that same tab is then used for a different website, the tiny image changes but the page is still not displayed correctly.

If, instead of clicking on the "Open" button, you right-click and select "Open Link in New Tab", the page is displayed correctly. The same tab can then be used successfully for other sites.

The problem does not occur on an iMac High Sierra.

**Comment by benbasson** [comment]
To help determine if this is a problem with my add-on code, or Firefox, or something else, can you please let me know what your homepage is set to? If you don't want to post it here, please feel free to contact me separately.

**Comment by Hilary247** [comment]
My home page is set to https://www.google.co.uk/

**Comment by hfgrimm** [comment]
My home page is set to:     file:///C:/www/hfgrimmfam.html <file:///C:\www\hfgrimmfam.html>

**Comment by benbasson** [comment]
hfgrimm, your problem is different, please see #24
