### ISSUE TITLE
URL displayed in address bar when opening a new tab

### ISSUE THREAD

**Issue by yellow-sock** [benbasson/newtabhomepage#27]
Thanks for this addon. This is more a feature request than a bug.

I have the habit when opening a new tab to enter a search expression in the address bar - as a fast way of searching. This works well for example in Chrome because the address bar does not contain any text after I opened a new tab even if the tab is configured to display a certain website.

With this addon I have to delete first the address of the site that is displayed before I can enter a search expression - not a massive issue but it would be more convenient if this would work like in Chrome.

**Comment by aivarsV** [comment]
With firefox 57, after page is loaded, focus is given to page.
Would be nice if, after page is loaded, foucus would still be assigned to address bar.

**Comment by benbasson** [comment]
This isn't something I can currently control. See issue #23 

If and when it's possible for this add-on to control the behaviour, it will, and I'll give users the option of how they want it to work.
