### ISSUE TITLE
URL is set to late after tab creation

### ISSUE THREAD

**Issue by xylo** [benbasson/newtabhomepage#28]
When I updated Firefox to version 57 I discovered a big regression: I cannot longer change the URL immediately after I created a new tab.

I used to press Ctrl+T, Ctrl+L to create a new tab and focus on the location bar where I could immediately enter my new URL or search string.  But this is not working anymore, because of several reasons:
* First of all, the address bar is usually not focused when pressing Ctrl+L.  For some reason I have to wait around 1 second after the tab creating until Ctrl+L works.
* Second of all, Firefox takes quite long (around 2 seconds) until it sets the URL to the start page that is loaded.  So I actually have to wait around 2 seconds to press Ctrl+L when I want to focus the address bar and select the URL.  This is very annoying.

**Comment by benbasson** [comment]
A couple of thoughts: 

1. Does this happen when New Tab Homepage is disabled, e.g. instead of opening a new tab, press the Home button and then try to Ctrl+L.
2. How long does your homepage take to load?

A consequence of the switch to the new APIs is that I can't intercept tab creation directly, I can only force all new tabs to open a page stored within the add-on, which then does a redirect to your chosen homepage. This is likely to add more delay, but not significantly.

In my experience, Firefox only seems to populate the URL bar once the page has fully loaded, you can see this on new tabs, e.g. when you Ctrl+click a link to a slow-loading page.

**Comment by xylo** [comment]
To 1.
When New Tab Homepage is disabled and I press the home button in an existing tab the behavior is very similar.  The only difference is that I can immediately focus the address bar with Ctrl+L.  But there is still the problem that the URL is set with a delay of around 1 second.

To 2.
When I put the address into an empty tab and press enter it takes around 2 seconds to load I would say.

> A consequence of the switch to the new APIs is that I can't intercept tab creation directly.

I think that's the main problem here.  With this new API users with slower computers can no longer use your plugin without major drawbacks.  That's a pity.  But thanks for the clarification.

My current solution is actually to deactivate your plugin, since it brings me at the moment more disadvantages than advantages. :-(

**Comment by dailytabs** [comment]
I ran into this as well. I try to go to sites like "youtube.comhttps://www.google.com" all the time :) It's really annoying.

I recently was forced to install Chrome and found out that https://github.com/jimschubert/newtab-redirect for Chrome does not suffer this problem. Maybe you can find something that he is doing that might help you in Firefox?

**Comment by benbasson** [comment]
That add-on is doing essentially exactly the same thing that I do in Firefox. Sadly, nobody seems to care about this requirement at Mozilla. 

Why someone bothered building this feature into an add-on for Chrome I don't understand, it's literally in the core Chrome settings. Mozilla should build in the functionality and make my add-on redundant, but it's been 15 years and I'm still waiting.

**Comment by benbasson** [comment]
That add-on is doing essentially exactly the same thing that I do in Firefox. Sadly, nobody seems to care about this requirement at Mozilla. I guess Chrome is just faster at executing it, especially on older/slower hardware.

Mozilla should build in the functionality and make my add-on redundant, but it's been 15 years and I'm still waiting.

**Comment by hfgrimm** [comment]
I have a privately created home page file on my computer.

I’m using “New Tab Start Page” extension on Chrome, I had to turn on “Allow access to file URLs” in it’s settings.

**Comment by benbasson** [comment]
I'm not doing any active development on this add-on - sorry, the Firefox APIs sucked at the time I had to update this, and I suspect they're no better now (no interest has been shown in accommodating this type of add-on or functionality)

**Comment by mrx23dot** [comment]
"Custom New Tab Page" works great, just need to select both options in settings.
Creates new tab, without filling url.
