### ISSUE TITLE
Does Not Work from Disc File with Ver 59.0.2

### ISSUE THREAD

**Issue by ghost** [benbasson/newtabhomepage#33]
Home page is:
file:///D:/User/Bob/Browser%20Bookmark%20Files/bookmarks.html
Firefox Quantum version is: 59.0.2 (64-bit) 

When a new tab loads, the page area is blank (all white), but none of the "bookmarks.html" file is present.  This file does load as the Home Page when the browser first starts up however.

Hope you can work this out,
Bob

**Comment by benbasson** [comment]
Sorry, Mozilla don't deem this appropriate behaviour for add-ons to support. I suggest you read issue #24 and take it up with Mozilla.
