### ISSUE TITLE
Stop working with firefox 60.0 update

### ISSUE THREAD

**Issue by suefreeman** [benbasson/newtabhomepage#34]
Firefox just updated to v60.0 (64bits)
NewTabHomepage stopped working.
it's the return of "Local Homepage" bug like https://github.com/benbasson/newtabhomepage/issues/24
It looks like it's trying to load but never get there ... (blank page)
(i have " ! " caracters and spaces in my local URL)
**edit:** i removed the " ! " caracters and spaces and it is still not working.

Thank you and good luck
Jay.

**Comment by Philip-Goddard** [comment]
I have this issue too. I just get a blank tab, failing to find the local web page that it always found before this last FF update. The path of my local file, which this extension now can't access, reads 

`D:\Websites\Website - Resources\reserve\sitemap-local.htm`

as I have it specified in FF Options, but of course it still reads as

`file:///D:/Websites/Website%20-%20Resources/reserve/sitemap-local.htm`

in the FF address bar.

I tried removing the spaces in the folder name and the path saved in Options, but that made no difference.

I do hope this issue can be fixed.

All the best,
Philip

**Comment by RenateUSB** [comment]
Firefox 60.0.1 (64 bit) broke this.
^T gets you a blank browser page with that stupid bouncing ball in the tab header.
You can hit ALT-Home and get your home page, an inconvenient extra step.

**Comment by benbasson** [comment]
Sorry, Mozilla don't deem this appropriate behaviour for add-ons to support. I suggest you read issue #24 and take it up with Mozilla.
