### ISSUE TITLE
Firefox Quantum 61.0.1 (32-bit) won't open a new tab to a local custom .htm file that I use as my homepage

### ISSUE THREAD

**Issue by Lifeblood2112** [benbasson/newtabhomepage#36]
I just updated from Firefox Quantum 59.0 (32-bit), which worked fine with New Tab Homepage 0.6.2, to Firefox Quantum 61.0.1 (32-bit), and now, when I try to open a new tab, it will no longer open a custom .htm file, that I use as my homepage.

I took and striped Yahoo's search bar from Yahoo's Search page, so I don't have to put up with any ads, or auto suggestions.  Then, I added a link to Yahoo Mail, and an envelope image next to it.  And that's it.  A very simple homepage.  It worked great until I updated.

Here's what it looks like
 
![homepage](https://user-images.githubusercontent.com/42022544/43565629-fe952a12-95f0-11e8-901b-c6266186dc24.jpg)

When I first start Firefox it still loads my homepage fine.  But, when I try to open a new tab, it just loads a blank page now.  Here's what that looks like.

![blank page](https://user-images.githubusercontent.com/42022544/43565673-21afe97e-95f1-11e8-803d-c5087ee35f9d.jpg)

Either Firefox is restricting access by add-ons to local files now.  Or, there is a problem with New Tab Homepage 0.6.2, working correctly with Firefox Quantum 61.0.1 (32-bit).

I should mention that I use this same .htm file for my homepage with Internet Explorer, Google Chrome, and Opera.  All of which are still working fine.  It's just the combination of New Tab Homepage 0.6.2 and Firefox Quantum 61.0.1 (32-bit) that is causing a problem.  I just can't tell if it's the browser, or the add-on, that is the problem.  I suspect that it's the add-on since Firefox still loads the homepage fine on it's own.  It's not until I try to open a new tab that it can't find the file and open it.

Could you please look into the problem and fix it?

Thanks

**Comment by benbasson** [comment]
Sorry, Mozilla don't deem this appropriate behaviour for add-ons to support. I suggest you read issue #24 and take it up with Mozilla.
