### ISSUE TITLE
extension just displays a white page

### ISSUE THREAD

**Issue by Patpoch** [benbasson/newtabhomepage#37]
Hi,
Linux mint 18.3 (up to date) , firefox 63.0 with newtabhomepage active.
my home page is a file (file:///home/userid/html/menu.html)
The extension ignores it and displays a white page.
Any idea about why this happens??
Thanks
Patrick

**Comment by nodet** [comment]
I also use a local file as my home page, and I confirm this incorrect behavior.
Using Firefox 60.3.0esr

**Comment by spschneer** [comment]
Same result on Windows 10, White page, no content, no URL fill, Using Firefox 70.0.1 (64-bit), Have a local file as my home page, and works properly as Firefox home page. Opening a tab, doesn't. 
Thanks

**Comment by benbasson** [comment]
Sorry, Mozilla don't deem this appropriate behaviour for add-ons to support. I suggest you read issue #24 and take it up with Mozilla.
