### ISSUE TITLE
The linked website gives me an internal server error

### ISSUE THREAD

**Issue by xaverdh** [benbasson/newtabhomepage#38]
Visiting http://www.basson.at/firefox-addons/newtabhomepage yields
`<h1>Internal Server Error</h1>` for me.

**Comment by dailytabs** [comment]
Still. To this day.

**Comment by benbasson** [comment]
It's broken and I don't have time to do anything about it. It's no major loss to the world, there was barely any content because this add-on has no preferences and only does one thing.
