### ISSUE TITLE
Firefox 75 new address bar makes the address expand until New Tab Homepage content isn't focused.

### ISSUE THREAD

**Issue by Blast-City** [benbasson/newtabhomepage#39]
Hi.

Firefox introduced a new address bar in version 75 that expands while it's focused. Since New Tab Homepage (thankfully) focus the content of the homepage, until it doesn't finish loading, the address bar is expanded for a brief moment, which makes it look ugly.

Is this something that could be fixed or something that we have to learn to live with it? 

Thanks for your work on this great extension.

**Comment by benbasson** [comment]
There is no control over any of this behaviour. Please see #23
