### ISSUE TITLE
Add option to select all immediately in address bar.

### ISSUE THREAD

**Issue by fizykz** [benbasson/newtabhomepage#44]
I'm sure many people can relate to this, but for myself I use this to open up an extension (Tab Stash).  This of course fills the address bar and places the cursor at the beginning.  Often however I'm not interacting with the tab but instead typing in the search bar.  Would it be possible to make it automatically do "Select All" (Ctrl+A) when a new tab is made in the address bar?  Would be a handy little feature :)

Thanks for such a straight forward extension btw.

**Comment by mrx23dot** [comment]
yes please!

so annoying
Or better keep url empty

**Comment by benbasson** [comment]
I'm not doing any active development on this add-on - sorry, the Firefox APIs sucked at the time I had to update this, and I suspect they're no better now (no interest has been shown in accommodating this type of add-on or functionality).

Last time I looked, what you're asking for simply wasn't possible.

**Comment by mrx23dot** [comment]
No worries, please update Readme to "Custom New Tab Page" as a successor, it works great.
