### ISSUE TITLE
doesn't work?

### ISSUE THREAD

**Issue by afmeyers** [benbasson/newtabhomepage#5]
A zombie now has my Firefox 41.0.2 opening new tabs on an unwanted search page.  I've installed newtabhomepage and it doesn't work - I still get the zombie page.  Any thoughts?  and thanks for doing this - it's the extension I want and need, but it just isn't working

**Comment by benbasson** [comment]
My add-on does one thing and one thing only, override the "new tab" page to be your homepage. 

I would suggest seeking help on https://support.mozilla.org/en-US/ - they'll be able to assist you more than I ever could.
