### ISSUE TITLE
Skips URL Select in Firefox Developer Edition 64bit.

### ISSUE THREAD

**Issue by Squire4Hire** [benbasson/newtabhomepage#8]
When a new tab is created in Firefox Developer Edition 64bit, the URL of the home page no longer remains selected which forces the user to select and delete the text prior to writing in a new URL.

**Comment by benbasson** [comment]
Works for me with New Tab Homepage 0.5.1 and 45.0a2 64-bit. Can you please re-test / give me more information on what version(s) you're using?
