### ISSUE TITLE
Incompatible with latest Firefox version

### ISSUE THREAD

**Issue by ghost** [benbasson/newtabhomepage#9]
> Works with Firefox 41.0a2 - 43.*

This doesn't include the latest ESR version of Firefox while the add-on is very likely compatible with it.
It causes Mozilla to deliver old versions to ESR users.
I personally use ESR because I'm not interested in Mozilla's experiments or in downloading a huge update every 6 weeks. Others feel the same or are limited by organisations who can't update Firefox as frequently.

**Comment by benbasson** [comment]
I fundamentally rewrote the add-on to make use of new Firefox APIs, so the latest version of New Tab Homepage is not compatible with versions of Firefox prior to 41.0a2. 

Users of older versions of Firefox, including the most recent ESR, should continue to use the previous version of New Tab Homepage. They're not losing out by doing so, the new versions have no more functionality.

**Comment by ghost** [comment]
Sounds good. Thanks for the fast and comprehensive answer. Keep up the great work. :smiley:
